os:
  - osx
language: swift
osx_image: xcode11.3
install: 
  - swift package update
  - swift package generate-xcodeproj
xcode_project: UNogsAPI.xcodeproj # path to your xcodeproj folder
xcode_scheme: UNogsAPI-Package
xcode_destination: platform=iOS Simulator,OS=13.2,name=iPad Pro (9.7-inch)
